services:
  one:
    image: study
    environment:
      NAME: gamma-one
  two:
    image: study
    hostname: twenty
    environment:
      NAME: gamma-two
    networks:
      default: {}
      alpha-net:
        aliases:
          - gamma-twenty

networks:
  alpha-net:
    name: alpha-net
    external: true
