services:
  one:
    image: study
    environment:
      NAME: omega-one
  two:
    image: study
    environment:
      NAME: omega-one
    networks:
      default: {}
      alpha-net:
        aliases:
          - twenty

networks:
  alpha-net:
    name: alpha-net
    external: true
